#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "bf1bad45e2b664b50c6b04a414ca96c739279ba5a14d685ba90904af8427d9f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python >=3.5
    - pip
    - setuptools

  run:
    - python >=3.5
    - setuptools
    - twisted >=17.9.0
    - w3lib >=1.17.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - parsel >=1.5.0
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]
    - protego

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    - brotlipy  # [win]
    - pip
  source_files:
    - conftest.py
    - scrapy
    - tests
  commands:
    - scrapy version  # [not win]
    - pip install setuptools-scm  # required by indirect dependency pytest-forked
    - pip install -ctests/constraints.txt -rtests/requirements-py3.txt Pillow botocore google-cloud-storage
    - mv scrapy _scrapy
    - rm tests/test_command_parse.py tests/test_command_shell.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py tests/test_exporters.py tests/test_feedexport.py tests/test_proxy_connect.py tests/test_utils_trackref.py  # [win]
    - rm tests/test_command_parse.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py  # [osx]
    - pytest _scrapy tests

about:
  home: https://scrapy.org/
  license: BSD 3-Clauses
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - redapple
    - kmike
    - Gallaecio
    - wRAR
    - dangra
